coverage:
  status:
    # pull-requests only
    patch:
      default:
        threshold: 0.2%
ignore:
  - "brcc-core/src/main/java/com/baidu/brcc/dao/**/*"
  - "brcc-core/src/main/java/com/baidu/brcc/domain/**/*"
