rcc:
  cc-server-url: http://rcc2.baidu-int.com
  cc-password: 123456
  logProperties: true
  projectName: test-rcc
  env-name: dev
  cc-version-name: 1.0.0
  enableUpdateCallback: true
  appName: example

