apiVersion: v1
kind: Service
metadata:
  name: brcc-service
  labels:
    app: brcc
    module: brcc-server
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 8080
      name: http
  selector:
    app: brcc
    module: brcc-server